name: Test build
on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch:
jobs:
  test-build:
    runs-on: ubuntu-22.04
    environment: test
    env:
      root_password: ${{ secrets.ROOT_PASSWORD }}
      user_name: ${{ secrets.USER_NAME }}
      user_password: ${{ secrets.USER_PASSWORD }}
      user_id: ${{ secrets.USER_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: 3.12.1
      - name: Install Python script package dependencies
        run: |
          python -m pip install -r scripts/python/requirements-base.txt && \
          python -m pip install -r scripts/python/requirements.txt
      - name: Add PYTHONPATH
        run: echo "PYTHONPATH=$PWD/scripts/python" >> "$GITHUB_ENV"
      - name: Run Python unit tests
        run: python tests/python/user_data_json_unit_tests.py
      - name: Create directory to store user data JSON files 
        run: mkdir -p data/json
      - name: Create root user data JSON file 
        run: |
          python scripts/python/user_data_json.py \
          --user=root \
          --password="$root_password" \
          > data/json/root_data.json
      - name: Create non-root user data JSON file 
        run: |
          python scripts/python/user_data_json.py \
          --user="$user_name" \
          --password="$user_password" \
          > data/json/user_data.json
      - name: Build container image
        run: |
          docker image build \
          --build-arg userid="$user_id" \
          --build-arg username="$user_name" \
          --secret id=root_data,src=data/json/root_data.json \
          --secret id=user_data,src=data/json/user_data.json \
          --tag ubuntu-userland:test .
      - name: Run test container
        run: |
          docker container run \
          --name ubuntu-userland \
          --detach \
          --tty \
          ubuntu-userland:test
      - name: Test root password
        run: |
          root_password_test=$( \
          docker container exec -i ubuntu-userland \
          bash -c \
          "echo ${root_password} | su - root -c whoami") ; \
          if [[ $root_password_test = "root" ]] ; then \
            exit 0 ; \
          else \
            exit 1 ; \
          fi
      - name: Test user password
        run: |
          user_password_test=$( \
          docker container exec -i ubuntu-userland \
          bash -c \
          "echo ${user_password} | su - ${user_name} -c whoami") ; \
          if [[ $user_password_test = "$user_name" ]] ; then \
            exit 0 ; \
          else \
            exit 1 ; \
          fi
      - name: Remove running container image
        run: docker container rm --force ubuntu-userland
      - name: Remove container image
        run: docker image rm ubuntu-userland:test
